name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore InfiniTicTacToe.Server/InfiniTicTacToe.Server.csproj

    - name: Build
      run: dotnet build InfiniTicTacToe.Server/InfiniTicTacToe.Server.csproj --configuration Release --no-restore

    - name: Restore test dependencies
      run: dotnet restore InfiniTicTacToe.Tests/InfiniTicTacToe.Tests.csproj

    - name: Build tests
      run: dotnet build InfiniTicTacToe.Tests/InfiniTicTacToe.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --no-build --verbosity normal
